services:
  flask:
    build: .
    container_name: flask
    networks:
      - ecommerce_network
    depends_on:
      - db
    working_dir: /webapp

  nginx:
    image: nginx:latest
    build : ./nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - flask
    networks:
      - ecommerce_network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf.d/:ro
      - ${WORKSPACE}/flask/static:/usr/share/nginx/html/static:ro

  db:
    image: mysql:5.7
    container_name: db
    env_file:
      - .env
    ports:
      - "3306:3306"
    networks:
      - ecommerce_network
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ADMIN_USER=${MYSQL_ADMIN_USER}
      - MYSQL_ADMIN_PASSWORD=${MYSQL_ADMIN_PASSWORD}
      - MYSQL_HOST=${MYSQL_HOST}
      - OUTLOOK_EMAIL=${OUTLOOK_EMAIL}
      - OUTLOOK_PASSWORD=${OUTLOOK_PASSWORD}
      - RECAPTCHA_PUBLIC_KEY=${RECAPTCHA_PUBLIC_KEY}
      - RECAPTCHA_PRIVATE_KEY=${RECAPTCHA_PRIVATE_KEY}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
    volumes:
      - mysql-data:/var/lib/mysql

networks:
  ecommerce_network:
    driver: bridge

volumes:
  mysql-data:
  jenkins_home:
