services:
  flask:
    build: .
    container_name: flask
    networks:
      - ecommerce_network
    depends_on:
      - db
    working_dir: /webapp
    environment:
      - DB_HOST=host.docker.internal  # Ensures flask connects to localhost db
      - DB_PORT=3306

  nginx:
    image: nginx:latest
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - flask
    networks:
      - ecommerce_network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro


  db:
    image: mysql:8.4
    container_name: db
    env_file:
      - .env
    ports:
      - "3306:3306"
    environment:
      - DB_HOST=host.docker.internal  # Connects to local MySQL
      - DB_PORT=3306
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}  # Required for MySQL initialization
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    command: ["mysqld", "--mysql-native-password=ON"]
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - ecommerce_network

networks:
  ecommerce_network:
    driver: bridge

volumes:
  mysql-data:
  jenkins_home:
