version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:8000"
    env_file:
      - .env
    volumes:
      - .:/webapp
    environment:
      - GUNICORN_CMD_ARGS=--reload --workers 3 --bind 0.0.0.0:8000
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
