services:
  flask:
    build: .
    container_name: flask
    networks:
      - ecommerce_network
    working_dir: /webapp
    env_file:
      - .env

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - flask
    networks:
      - ecommerce_network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

networks:
  ecommerce_network:
    driver: bridge
