version: '3.8'

services:
  web:
    container_name: flask
    image: python:3.9
    command: bash -c "pip install gunicorn && while [ ! -f /app/.env ]; do sleep 1; done && gunicorn --bind 0.0.0.0:8000 main:app"
    volumes:
      - ./flask:/app
    networks:
      - ecommerce_network
    env_file:
      - .env
    working_dir: /app

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    networks:
      - ecommerce_network
    volumes:
      - ./flask/static:/app/static
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /path/to/ssl/certs:/etc/ssl/cert
      - /path/to/ssl/private:/etc/ssl/private

  db:
    image: mysql:5.7
    container_name: mysql
    env_file:
      - .env
    ports:
      - "3306:3306"
    networks:
      - ecommerce_network
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_BOUNDARY}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_USER_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql

networks:
  ecommerce_network:
    driver: bridge

volumes:
  mysql-data:
