version: '3.8'

services:
  web:
    build: .
    container_name: flask
    command: gunicorn --bind 0.0.0.0:8000 run:app
    volumes:
      - .:/app
    networks:
      - my_custom_network
    secrets:
      - secret_key
      - mysql_root_password
      - mysql_database
      - mysql_admin_user
      - mysql_admin_password
      - mysql_merchant_user
      - mysql_merchant_password
      - mysql_user
      - mysql_user_password
      - mysql_readonly_user
      - mysql_readonly_password
      - mysql_host

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    networks:
      - my_custom_network
    volumes:
      - ./static:/app/static
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /path/to/ssl/certs:/etc/ssl/certs
      - /path/to/ssl/private:/etc/ssl/private

  db:
    image: mysql:5.7
    container_name: mysql
    secrets:
      - mysql_root_password
      - mysql_database
      - mysql_admin_user
      - mysql_admin_password
      - mysql_merchant_user
      - mysql_merchant_password
      - mysql_user
      - mysql_user_password
      - mysql_readonly_user
      - mysql_readonly_password
      - mysql_host
    ports:
      - "3306:3306"
    networks:
      - my_custom_network
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
    networks:
      - my_custom_network
    environment:
      JENKINS_OPTS: --httpPort=8080
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  my_custom_network:
    driver: bridge

volumes:
  jenkins_home:

secrets:
  secret_key:
    external: true
  mysql_root_password:
    external: true
  mysql_database:
    external: true
  mysql_admin_user:
    external: true
  mysql_admin_password:
    external: true
  mysql_merchant_user:
    external: true
  mysql_merchant_password:
    external: true
  mysql_user:
    external: true
  mysql_user_password:
    external: true
  mysql_readonly_user:
    external: true
  mysql_readonly_password:
    external: true
  mysql_host:
    external: true
