version: '3.8'

services:
  flask:
    build: .
    container_name: flask
    image: python:3.9
    command: bash -c "pip install gunicorn && while [ ! -f /app/.env ]; do sleep 1; done && gunicorn --workers 3 --bind 0.0.0.0:8000 app:app"
    networks:
      - ecommerce_network
    env_file:
      - .env
    depends_on:
      - db
    working_dir: /app

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - flask
    networks:
      - ecommerce_network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ${WORKSPACE}/flask/static:/usr/share/nginx/html/static:ro

  db:
    image: mysql:5.7
    container_name: db
    env_file:
      - .env
    ports:
      - "3306:3306"
    networks:
      - ecommerce_network
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ADMIN_USER=${MYSQL_ADMIN_USER}
      - MYSQL_ADMIN_PASSWORD=${MYSQL_ADMIN_PASSWORD}
      - MYSQL_MERCHANT_USER=${MYSQL_MERCHANT_USER}
      - MYSQL_MERCHANT_PASSWORD=${MYSQL_MERCHANT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_USER_PASSWORD=${MYSQL_USER_PASSWORD}
      - MYSQL_READONLY_USER=${MYSQL_READONLY_USER}
      - MYSQL_READONLY_PASSWORD=${MYSQL_READONLY_PASSWORD}
      - MYSQL_HOST=${MYSQL_HOST}
    volumes:
      - mysql-data:/var/lib/mysql

networks:
  ecommerce_network:
    driver: bridge

volumes:
  mysql-data:
  jenkins_home:
